name: Docker with Nginx

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]

jobs:
  docker:
    if: |
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Login to Docker
      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build image
      - name: Build Docker Image
        run: docker build -t mynginx:test .

      # Test Image
      - name: Test Docker build image
        run: |
          docker run -d -p 8080:80 --name test-nginx mynginx:test
          sleep 5
          curl http://localhost:8080 | grep "Hello from GitHub Actions"
          docker stop test-nginx
   
      # Push Image
      - name:  Push to DockerHub
        run: |
            docker tag mynginx:test ${{ secrets.DOCKER_USERNAME }}/mynginx:latest
            docker push ${{ secrets.DOCKER_USERNAME }}/mynginx:latest
      
